export const HomeContent = [
  {
    name: "HTML",
    image:
      "https://tse4.mm.bing.net/th?id=OIP.Q-H2vvVR-4JY1xRBbWI84QHaDf&pid=Api&P=0&w=398&h=188",
    title: "The Language For Building Web Page",
    description:
      "HTML stands for Hyper Text Markup Language, which is the most widely used language on Web to develop web pages. HTML was created by Berners-Lee in late 1991 but 'HTML 2.0' was the first standard HTML specification which was published in 1995. HTML 4.01 was a major version of HTML and it was published in late 1999. Though HTML 4.01 version is widely used but currently we are having HTML-5 version which is an extension to HTML 4.01, and this version was published in 2012.",
    gotolearnpage: "Learn html",
  },
  {
    name: "CSS",
    image:
      "http://constructs.stampede-design.com/wp-content/uploads/2014/10/css3.jpg",
    title: "The Language For styling Web Page",
    description:
      "Cascading Style Sheets, fondly referred to as CSS, is a simple design language intended to simplify the process of making web pages presentable.CSS handles the look and feel part of a web page. Using CSS, you can control the color of the text, the style of fonts, the spacing between paragraphs, how columns are sized and laid out, what background images or colors are used, layout designs,variations in display for different devices and screen sizes as well as a variety of other effects.CSS is easy to learn and understand but it provides powerful control over the presentation of an HTML document. Most commonly, CSS is combined with the markup languages HTML or XHTML.",
    gotolearnpage: "Learn CSS",
  },
  {
    name: "JAVASCRIPT",
    image: "https://miro.medium.com/max/750/1*qa4OJKpAO5NDgaiby7OHdw.jpeg",
    title: "The Language For programming Web Page",
    description:
      "JavaScript is a dynamic computer programming language. It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.",
    gotolearnpage: "Learn JavaScript",
  },
  {
    name: "BOOTSTRAP",
    image:
      "https://s3.amazonaws.com/storage.blog.thesiteslinger.com/uploads/2013/08/Twitter-Bootstrap-Logo.jpg",
    title: "A css framework For Building better Web Page",
    description:
      "Bootstrap is the most popular HTML, CSS and JavaScript framework for developing a responsive and mobile friendly website.It is absolutely free to download and use.It is a front-end framework used for easier and faster web development.It includes HTML and CSS based design templates for typography, forms, buttons, tables, navigation, modals, image carousels and many others.It can also use JavaScript plug-ins.It facilitates you to create responsive designs.",
    gotolearnpage: "Learn Bootstrap",
  },
  {
    name: "REACT.JS",
    image:
      "https://tse1.mm.bing.net/th?id=OIP.vHHBwcUFUaHWXntSnqKdCAHaEK&pid=Api&P=0&w=314&h=177",
    title: "A Javascript framework For Building Web Page",
    description:
      "ReactJS is a declarative, efficient, and flexible JavaScript library for building reusable UI components. It is an open-source, component-based front end library responsible only for the view layer of the application. It was created by Jordan Walke, who was a software engineer at Facebook. It was initially developed and maintained by Facebook and was later used in its products like WhatsApp & Instagram. Facebook developed ReactJS in 2011 in its newsfeed section, but it was released to the public in the month of May 2013.Today, most of the websites are built using MVC (model view controller) architecture. In MVC architecture, React is the 'V' which stands for view, whereas the architecture is provided by the Redux or Flux.A ReactJS application is made up of multiple components, each component responsible for outputting a small, reusable piece of HTML code. The components are the heart of all React applications. These Components can be nested with other components to allow complex applications to be built of simple building blocks. ReactJS uses virtual DOM based mechanism to fill data in HTML DOM. The virtual DOM works fast as it only changes individual DOM elements instead of reloading complete DOM every time.",
    gotolearnpage: "Learn React.Js",
  },
  {
    name: "NODE.JS",
    image:
      "https://www.paceit.co.uk/wp-content/uploads/2019/08/node-js-logo.jpg",
    title: "The Language For server side programming",
    description:
      "Node.js is a server-side platform built on Google Chrome's JavaScript Engine (V8 Engine). Node.js was developed by Ryan Dahl in 2009 and its latest version is v0.10.36. The definition of Node.js as supplied by its official documentation is as follows −Node.js is a platform built on Chrome's JavaScript runtime for easily building fast and scalable network applications. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient, perfect for data-intensive real-time applications that run across distributed devices.Node.js is an open source, cross-platform runtime environment for developing server-side and networking applications. Node.js applications are written in JavaScript, and can be run within the Node.js runtime on OS X, Microsoft Windows, and Linux.",
    gotolearnpage: "Learn Node.Js",
  },
  {
    name: "MONGODB",
    image:
      "https://tse1.mm.bing.net/th?id=OIP.nBeBfa7LNZh43JjMULFdyAAAAA&pid=Api&P=0&w=340&h=155",
    title: "The language for storing the database",
    description:
      "MongoDB is a cross-platform, document oriented database that provides, high performance, high availability, and easy scalability. MongoDB works on concept of collection and document.Database Database is a physical container for collections. Each database gets its own set of files on the file system. A single MongoDB server typically has multiple databases.Collection is a group of MongoDB documents. It is the equivalent of an RDBMS table. A collection exists within a single database. Collections do not enforce a schema. Documents within a collection can have different fields. Typically, all documents in a collection are of similar or related purpose.A document is a set of key-value pairs. Documents have dynamic schema. Dynamic schema means that documents in the same collection do not need to have the same set of fields or structure, and common fields in a collection's documents may hold different types of data.The following table shows the relationship of RDBMS terminology with MongoDB.",
    gotolearnpage: "Learn MongoDb",
  },
];
